version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: library
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
    networks:
      - symfony_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/symfony-app
    volumes:
      - ./:/var/www/symfony-app
    depends_on:
      - postgres
    networks:
      - symfony_network
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/library_db"
      APP_ENV: prod
    command: >
      bash -c "php bin/console doctrine:migrations:migrate --no-interaction && php-fpm"

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - ./public:/var/www/symfony-app/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    depends_on:
      - app
    networks:
      - symfony_network
    ports:
      - "80:80"
    
volumes:
  postgres_data:

networks:
  symfony_network:
    driver: bridge